"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

palette = 'dracula'

format = """
[╭─](foreground bold)$os\
$sudo\
$username\
$hostname\
$directory\
\n[╰─> ](foreground bold)
"""

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

[os]
format = "[$symbol]($style)"
style = 'cyan bold'
disabled = false

[os.symbols]
Arch = "  "

[username]
style_root = 'red bold'
style_user = 'green bold'
format = '[$user]($style)[@](foreground bold)'
show_always = true

[hostname]
ssh_only = false
ssh_symbol = ' '
format = '[$hostname]($style)[$ssh_symbol](foreground bold) '
style = 'green bold'

[sudo]
format = "[\\[](foreground bold)[sudo]($style)[\\]](foreground bold)"
style = 'red bold'
disabled = false

[directory]
truncation_length = 10
truncate_to_repo = false
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'comment bold'
read_only = ' '
read_only_style = 'red bold'
truncation_symbol = '../'
